var answers= [
	            	"He is a sophomore at Stanford", //1
                    "He is an 18 years old boy",
                    "He speaks English and Hindi",
                    "He can code in C++, Java, Javascript, C#, etc",
                    "He knows Unity3D, Xcode, Photoshop, etc.",
                    "His goal in life is to write beautiful code, which will impact peoples lives",
                    "Google is an innovative company and a place Rishab will love to work at",
                    "Rishab has several accomplishments. For more details refer to his resume at: rishab.me/resume",
                    "Rishab is pursuing an undergraduate computer science degree, and will probably do a track in Artificial intelligence",
                    "Rishab looks up to, and is inspired by Steve Jobs", //10
                    "The heights of greatmen reached and achieved, not by a sudden flight, but the while their companions slept while toiling upwards in the night.",
                    "For private details like these please contact Rishab at rishab@stanford.edu ",
                    "Rishab's mom is Shalini Mehra",
                    "Rishab's dad is Ajay Mehra",
                    "His permanent address is in new Delhi, but he is currently living in California for studies. If you want to send him a gift please send at 531 Lausen Mall, P.O. Box 18043, Stanford, CA - 94309",
                    "His dogs name is Shiro. He is a 1 year old Bolognese. Rishab, also loves his previous dog - Candy",
                    "His favourite food is butter chicken with butter naan.",
                    "He loves chocolate ice cream",
                    "Rishab is 5 feet 9 inches",
                    "He weighs around 60 kgs", //20
                    "His favorite book is The Hunger Games - Catching Fire",
                    "His favourite movie is Inception",
                    "Rishabs favorite TV show is The Game of Thrones",
                    "Rishab currently owns a MacBook Pro 15 inch with Retina display, 16 GB RAM and a 256 MB hard drive",
                    "Rishab owns an iPhone 5S right now and has ordered an iPhone 6S, which should arrive soon",
                    "Rishab has a little sister, Anaika",
                    "He was born on 13th November 1996",
                    "Rishab's name is.... Rishab ... Rishab Mehra ...",
                    "Rishab's favorite website is Emirates Airlines.",
                    "He loves Hershey's Kisses", //30
                    "Rishab loves to code random projects like me. He also loves trying out new sports.",
                    "Rishab hopes to live a nice and happy life, with a lot of close friends and family to enjoy it with.",
                    "He is currently not working since he is at college, but is seeking for a summer internship.",
                    "Rishab has worked on several projects. To view details about them please visit: rishab.me/resume ",
                    "Rishab was a national level athlete back in India and has several sports achievements. He continues to work out at the gym daily and try out new sports. To knw more about Rishab's sports achievements please visit the following link: ",
                    "Rishab loves party music, rock and EDM. Currently his favorite song is Somebody by Natalie La Ross and Jeremih",
                    "He loves oranges, apples, grapes, pomegrenade and grapefruit",
                    "Dont talk about vegetables here. My master will be upset",
                    "Emma Watson!",
                    "All this is a topic of the past", //40
                    "Rishab has over a 3.7 GPA as of now",
                    "He enjoyed most learning CS 103 from Keith Swartz",
                    "Rishab is an Indian citizen.",
                    "Rishab is a high school graduate, currently pursuing an undergraduate degree in Computer Science.",
                    "He is a Indian boy studying in US. If you have specific questions about him, please ask.",
                    "You can find his resume at: rishab.me/resume",
                    "Rishab wears Size 9 shoes. He loves Nike in particular.",
                    "Rishab wears medium"
					                    
             ];